# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoPorCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha', models.DateField(verbose_name='Fecha de Imputación')),
                ('importe_ars', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe (ARS)')),
                ('importe_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Importe (USD)')),
                ('tipo_origen', models.CharField(choices=[('MANO_DE_OBRA', 'Mano de Obra (Jornales/Horas)'), ('INSUMO', 'Insumos Agrícolas (Agroquímicos/Fertilizantes)'), ('COMBUSTIBLE', 'Combustible y Maquinaria'), ('CONTRATISTA', 'Servicios de Contratistas / Terceros'), ('ENERGIA_RIEGO', 'Energía Eléctrica y Riego'), ('MANTENIMIENTO', 'Mantenimiento y Reparaciones'), ('ESTRUCTURA_ADMIN', 'Costos de Estructura / Administración')], max_length=30, verbose_name='Tipo de Origen / Concepto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción / Detalle')),
                ('documento_origen_tipo', models.CharField(blank=True, help_text='Ej: ParteDiario, MovimientoStock, FacturaProveedor', max_length=50, verbose_name='Tipo de Documento Origen')),
                ('documento_origen_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Documento Origen')),
                ('centro_de_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_registrados', to='core.centrodecosto', verbose_name='Centro de Costo')),
                ('cuadro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_directos', to='campos.cuadro', verbose_name='Cuadro / Cuartel (opcional si es directo)')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_finca', to='core.finca', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Costo por Centro',
                'verbose_name_plural': 'Costos por Centro',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['centro_de_costo', 'fecha'], name='costos_cost_centro__3cd701_idx'), models.Index(fields=['finca', 'fecha'], name='costos_cost_finca_i_77c330_idx'), models.Index(fields=['cuadro', 'fecha'], name='costos_cost_cuadro__6c64dd_idx'), models.Index(fields=['documento_origen_tipo', 'documento_origen_id'], name='costos_cost_documen_322956_idx')],
            },
        ),
    ]
