# Generated by Django 5.1.15 on 2026-09-21 15:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_cuentas_contables(apps, schema_editor):
    CostoPorCentro = apps.get_model('costos', 'CostoPorCentro')
    CuentaContable = apps.get_model('finanzas', 'CuentaContable')
    
    # Diccionario de cuentas imputables en memoria
    cuentas = {c.codigo: c for c in CuentaContable.objects.filter(codigo__startswith='4.')}
    if not cuentas:
        return

    cta_agro_sueldos = cuentas.get('4.2.1.01.000000')
    cta_agro_insumos = cuentas.get('4.2.1.02.000000')
    cta_agro_cosecha_terc = cuentas.get('4.2.1.05.000000')
    cta_agro_fletes = cuentas.get('4.2.1.06.000000') or cta_agro_insumos
    cta_agro_mantenim = cuentas.get('4.2.1.07.000000') or cta_agro_insumos
    cta_alm_sueldos = cuentas.get('4.2.2.01.000000') or cta_agro_sueldos
    cta_alm_energia = cuentas.get('4.2.2.02.000000') or cta_agro_insumos
    cta_alm_mantenim = cuentas.get('4.2.2.03.000000') or cta_agro_mantenim
    cta_admin = cuentas.get('4.2.5.01.000000') or cta_agro_sueldos

    for costo in CostoPorCentro.objects.filter(cuenta_contable__isnull=True):
        tipo_cc = costo.centro_de_costo.tipo if costo.centro_de_costo else 'PRODUCTIVO_CAMPO'
        
        if costo.tipo_origen == 'MANO_DE_OBRA':
            if tipo_cc == 'FABRICA_ALMAZARA':
                costo.cuenta_contable = cta_alm_sueldos
            elif tipo_cc == 'ESTRUCTURA_ADMIN':
                costo.cuenta_contable = cta_admin
            else:
                costo.cuenta_contable = cta_agro_sueldos
        elif costo.tipo_origen == 'INSUMO':
            costo.cuenta_contable = cta_agro_insumos
        elif costo.tipo_origen == 'COMBUSTIBLE':
            costo.cuenta_contable = cta_agro_fletes
        elif costo.tipo_origen == 'CONTRATISTA':
            costo.cuenta_contable = cta_agro_cosecha_terc
        elif costo.tipo_origen == 'ENERGIA_RIEGO':
            if tipo_cc == 'FABRICA_ALMAZARA':
                costo.cuenta_contable = cta_alm_energia
            else:
                costo.cuenta_contable = cta_agro_insumos
        elif costo.tipo_origen == 'MANTENIMIENTO':
            if tipo_cc == 'FABRICA_ALMAZARA':
                costo.cuenta_contable = cta_alm_mantenim
            else:
                costo.cuenta_contable = cta_agro_mantenim
        elif costo.tipo_origen == 'ESTRUCTURA_ADMIN':
            costo.cuenta_contable = cta_admin
        else:
            costo.cuenta_contable = cta_agro_insumos

        if costo.cuenta_contable:
            costo.save(update_fields=['cuenta_contable'])


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_eventocuadro_registrofenologico'),
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('costos', '0001_initial'),
        ('finanzas', '0005_tipocambiomensual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costoporcentro',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Costo por Centro', 'verbose_name_plural': 'Costos por Centro'},
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='costo_origen_prorrateo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_hijos_prorrateados', to='costos.costoporcentro', verbose_name='Costo Indirecto Origen'),
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable del Rubro 4 (Egresos) a la que se imputa este costo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_imputados', to='finanzas.cuentacontable', verbose_name='Cuenta Contable (Plan de Cuentas)'),
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='es_prorrateado',
            field=models.BooleanField(default=False, help_text='Indica si este costo proviene del prorrateo de un gasto indirecto o común.', verbose_name='¿Es Prorrateado?'),
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='movimiento_financiero',
            field=models.ForeignKey(blank=True, help_text='Egreso de caja o cuenta bancaria si fue abonado al contado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_asociados', to='finanzas.movimientofinanciero', verbose_name='Movimiento Financiero (Caja/Banco)'),
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='prorrateo_realizado',
            field=models.BooleanField(default=False, help_text='Indica si este costo indirecto ya fue distribuido entre los cuadros de la finca.', verbose_name='¿Prorrateo Realizado?'),
        ),
        migrations.AddField(
            model_name='costoporcentro',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor o contratista emisor del comprobante o servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_proveedor', to='finanzas.cuentacorriente', verbose_name='Proveedor / Contratista Vinculado'),
        ),
        migrations.AddIndex(
            model_name='costoporcentro',
            index=models.Index(fields=['cuenta_contable', 'fecha'], name='costos_cost_cuenta__5e09fb_idx'),
        ),
        migrations.RunPython(backfill_cuentas_contables, migrations.RunPython.noop),
    ]
