# Generated by Django 5.1.15 on 2026-09-28 00:18

from django.db import migrations, models



def asignar_campana_historica(apps, schema_editor):
    CostoPorCentro = apps.get_model('costos', 'CostoPorCentro')
    costos = list(CostoPorCentro.objects.all())
    count = 0
    resumen = {}
    for costo in costos:
        if costo.fecha.month >= 7:
            campana = f"{costo.fecha.year}/{costo.fecha.year + 1}"
        else:
            campana = f"{costo.fecha.year - 1}/{costo.fecha.year}"
        costo.campana = campana
        resumen[campana] = resumen.get(campana, 0) + 1
        count += 1

    CostoPorCentro.objects.bulk_update(costos, ['campana'], batch_size=500)
    print("\n--- MIGRACION DE CAMPANAS DE COSTOS ---")
    print(f"Total registros actualizados: {count}")
    for k, v in sorted(resumen.items()):
        print(f"Campana {k}: {v} costos")
    print("---------------------------------------\n")

def revertir_campana(apps, schema_editor):
    CostoPorCentro = apps.get_model('costos', 'CostoPorCentro')
    CostoPorCentro.objects.update(campana='')

class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0006_add_precio_venta_estimado_lotecosecha'),
        ('core', '0004_empresa_condicion_iva_empresa_ingresos_brutos_and_more'),
        ('costos', '0002_relaciones_plan_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='costoporcentro',
            name='campana',
            field=models.CharField(blank=True, db_index=True, help_text='Ciclo jul-jun, ej: 2025/2026. Se asigna automáticamente desde la fecha si no se especifica.', max_length=20, verbose_name='Campaña Agrícola'),
        ),
        migrations.AddIndex(
            model_name='costoporcentro',
            index=models.Index(fields=['cuadro', 'campana'], name='costos_cost_cuadro__23ff81_idx'),
        ),
        migrations.AddIndex(
            model_name='costoporcentro',
            index=models.Index(fields=['campana'], name='costos_cost_campana_61cde2_idx'),
        ),
        migrations.RunPython(asignar_campana_historica, revertir_campana),
    ]
