# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=150, verbose_name='Nombre de Fantasía')),
                ('cuit', models.CharField(max_length=20, unique=True, verbose_name='CUIT')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección Legal')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('moneda_principal', models.CharField(default='ARS', max_length=5, verbose_name='Moneda Principal')),
                ('moneda_secundaria', models.CharField(default='USD', max_length=5, verbose_name='Moneda Secundaria')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de la Finca')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Finca')),
                ('superficie_total_ha', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Superficie Total (ha)')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación / Localidad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('tipo_riego_principal', models.CharField(choices=[('GOTEO', 'Riego por Goteo'), ('ASPERSION', 'Microaspersión'), ('SURCO', 'Manto / Surco'), ('MIXTO', 'Mixto'), ('SECANO', 'Secano')], default='GOTEO', max_length=20, verbose_name='Tipo de Riego Principal')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['nombre'],
                'permissions': (('administrar_finca', 'Puede administrar finca'), ('ver_finca', 'Puede ver datos de la finca')),
            },
        ),
        migrations.CreateModel(
            name='CentroDeCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código Contable')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Centro de Costo')),
                ('tipo', models.CharField(choices=[('PRODUCTIVO_CAMPO', 'Productivo Agrícola (Fincas/Cuadros)'), ('FABRICA_ALMAZARA', 'Fábrica / Almazara (Elaboración Aceite/Aceituna)'), ('MAQUINARIA_TALLER', 'Taller y Maquinaria'), ('ESTRUCTURA_ADMIN', 'Estructura y Administración'), ('COMERCIAL_EXPORT', 'Comercial y Exportación')], default='PRODUCTIVO_CAMPO', max_length=30, verbose_name='Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_de_costo', to='core.empresa', verbose_name='Empresa')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_de_costo', to='core.finca', verbose_name='Finca Asociada')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN_GENERAL', 'Administrador General'), ('RESPONSABLE_FINCA', 'Responsable de Finca'), ('ENCARGADO_CAMPO', 'Encargado de Campo'), ('INGENIERO_AGRONOMO', 'Ingeniero Agrónomo'), ('CONTABLE', 'Responsable Contable / Finanzas'), ('RRHH', 'Recursos Humanos'), ('OPERARIO', 'Operario / Capataz')], default='ADMIN_GENERAL', max_length=25, verbose_name='Rol en el Sistema')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('finca_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='core.finca', verbose_name='Finca Predeterminada')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
