# Generated by Django 5.1.15 on 2026-09-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0003_cuentacontable_cuenta_cuenta_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecosto',
            name='cuenta_contable_defecto',
            field=models.ForeignKey(blank=True, help_text='Cuenta de costo o gasto asociada habitualmente a este centro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_de_costo', to='finanzas.cuentacontable', verbose_name='Cuenta Contable por Defecto'),
        ),
    ]
