# Generated by Django 5.1.15 on 2026-09-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UID Supabase'),
        ),
    ]
