# Generated by Django 5.1.15 on 2026-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_supabase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='condicion_iva',
            field=models.CharField(default='Responsable Inscripto', max_length=100, verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ingresos_brutos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nro. Ingresos Brutos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inicio_actividades',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Actividades'),
        ),
    ]
