# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo_labor', models.CharField(choices=[('PODA_FORMACION', 'Poda de Formación'), ('PODA_PRODUCCION', 'Poda de Producción / Aclareo'), ('CURA_FITOSANITARIA', 'Cura Fitosanitaria (Repilo, Mosca, Cochinilla)'), ('FERTIRRIEGO', 'Fertirriego / Nutrición'), ('DESMALEZADO', 'Desmalezado Mecánico / Químico'), ('MANTENIMIENTO_RIEGO', 'Mantenimiento y Reparación de Riego'), ('COSECHA_MANUAL', 'Cosecha Manual'), ('COSECHA_MECANICA', 'Cosecha Mecanizada (Vibrador)'), ('LABOR_SUELO', 'Laboreo de Suelo / Subsolado'), ('OTRA', 'Otra Labor Agrícola')], max_length=35, verbose_name='Tipo de Labor')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('instrucciones_tecnicas', models.TextField(blank=True, help_text='Dosis, calibración de pulverizadora, recomendaciones de seguridad', verbose_name='Instrucciones Agronómicas')),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_EJECUCION', 'En Ejecución'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20, verbose_name='Estado')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='campos.cuadro', verbose_name='Cuadro')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agrónomo / Encargado Responsable')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='ParteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha', models.DateField(verbose_name='Fecha de Ejecución')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En Carga)'), ('CONFIRMADO_CERRADO', 'Confirmado y Cerrado')], default='BORRADOR', max_length=25, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Novedades de Campo')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cierre')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_diarios', to='campos.cuadro', verbose_name='Cuadro / Cuartel')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_diarios', to='core.finca', verbose_name='Finca')),
                ('orden_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_diarios', to='parte_diario.ordendetrabajo', verbose_name='Orden de Trabajo (opcional)')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Encargado / Supervisor')),
            ],
            options={
                'verbose_name': 'Parte Diario',
                'verbose_name_plural': 'Partes Diarios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParteDiarioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Utilizada')),
                ('dosis_por_hectarea', models.CharField(blank=True, max_length=50, verbose_name='Dosis / Ha')),
                ('costo_unitario_aplicado_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario al Cierre (ARS)')),
                ('costo_total_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Total Insumo (ARS)')),
                ('deposito_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito', verbose_name='Depósito de Retiro')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo', verbose_name='Insumo')),
                ('movimiento_stock_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientostock', verbose_name='Movimiento de Stock Asociado')),
                ('parte_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='parte_diario.partediario', verbose_name='Parte Diario')),
            ],
            options={
                'verbose_name': 'Insumo Utilizado en Parte',
                'verbose_name_plural': 'Insumos Utilizados en Partes',
            },
        ),
        migrations.CreateModel(
            name='ParteDiarioPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('horas_normales', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Horas Normales')),
                ('horas_extras', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Horas Extras')),
                ('tarea_especifica', models.CharField(blank=True, max_length=100, verbose_name='Labor Específica')),
                ('costo_jornal_calculado_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Jornal Imputado (ARS)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado', verbose_name='Empleado')),
                ('parte_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_asignado', to='parte_diario.partediario', verbose_name='Parte Diario')),
            ],
            options={
                'verbose_name': 'Personal en Parte Diario',
                'verbose_name_plural': 'Personal en Partes Diarios',
                'unique_together': {('parte_diario', 'empleado')},
            },
        ),
    ]
