# Generated by Django 5.1.15 on 2026-09-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_labor',
            field=models.CharField(choices=[('PODA_FORMACION', 'Poda de Formación'), ('PODA_PRODUCCION', 'Poda de Producción / Aclareo'), ('CURA_FITOSANITARIA', 'Cura Fitosanitaria (Repilo, Mosca, Cochinilla)'), ('FERTIRRIEGO', 'Fertirriego / Nutrición'), ('DESMALEZADO', 'Desmalezado Mecánico / Químico'), ('MANTENIMIENTO_RIEGO', 'Mantenimiento y Reparación de Riego'), ('RIEGO', 'Riego (Registro Hídrico)'), ('COSECHA_MANUAL', 'Cosecha Manual'), ('COSECHA_MECANICA', 'Cosecha Mecanizada (Vibrador)'), ('LABOR_SUELO', 'Laboreo de Suelo / Subsolado'), ('OTRA', 'Otra Labor Agrícola')], max_length=35, verbose_name='Tipo de Labor'),
        ),
        migrations.CreateModel(
            name='ParteDiarioRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo_agua', models.CharField(choices=[('POZO', 'Pozo Propio'), ('CANAL', 'Canal / Acequia'), ('RESERVORIO', 'Reservorio / Pileta'), ('RED', 'Red Pública')], default='POZO', max_length=15, verbose_name='Fuente de Agua')),
                ('horas_bomba', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Horas de Bomba')),
                ('caudal_m3_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Caudal (m³/hora)')),
                ('conductividad_electrica', models.DecimalField(blank=True, decimal_places=2, help_text='Medición de salinidad del agua de riego', max_digits=6, null=True, verbose_name='Conductividad Eléctrica (µS/cm)')),
                ('temperatura_agua', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp. Agua (°C)')),
                ('observaciones_riego', models.TextField(blank=True, verbose_name='Observaciones de Riego')),
                ('parte_diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_riego', to='parte_diario.partediario', verbose_name='Parte Diario')),
            ],
            options={
                'verbose_name': 'Datos de Riego',
                'verbose_name_plural': 'Datos de Riego',
            },
        ),
    ]
