# Generated by Django 5.1.15 on 2026-09-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_lotedecosecha_campos_lote_campana_da8d40_idx_and_more'),
        ('parte_diario', '0002_alter_ordendetrabajo_tipo_labor_partediarioriego'),
        ('personal', '0004_ordentrabajo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partediario',
            name='orden_de_trabajo',
        ),
        migrations.AddField(
            model_name='partediario',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_diarios', to='personal.ordentrabajo', verbose_name='Orden de Trabajo Semanal'),
        ),
        migrations.AlterField(
            model_name='partediario',
            name='cuadro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_diarios', to='campos.cuadro', verbose_name='Cuadro / Cuartel'),
        ),
        migrations.CreateModel(
            name='AvanceTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad_avanzada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('parte_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_tareas', to='parte_diario.partediario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='personal.tareaordentrabajo')),
            ],
            options={
                'verbose_name': 'Avance de Tarea',
                'verbose_name_plural': 'Avances de Tareas',
            },
        ),
    ]
