# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo_entidad', models.CharField(choices=[('PROVEEDOR', 'Proveedor (Insumos, Servicios, Contratistas)'), ('CLIENTE', 'Cliente (Aceitera, Mayorista, Exportación)')], max_length=20, verbose_name='Tipo de Entidad')),
                ('razon_social', models.CharField(max_length=180, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, verbose_name='Nombre Comercial')),
                ('cuit', models.CharField(max_length=20, unique=True, verbose_name='CUIT / Identificación Fiscal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección Comercial')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Para Proveedor: saldo negativo = debemos pagarle. Para Cliente: saldo positivo = nos debe cobrar.', max_digits=14, verbose_name='Saldo Actual')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Límite de Crédito')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes (Proveedores y Clientes)',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('CAJA_EFECTIVO', 'Caja Chica / Efectivo en Finca'), ('BANCO', 'Cuenta Corriente / Caja de Ahorro Bancaria'), ('VIRTUAL', 'Billetera Virtual / Mercado Pago')], default='BANCO', max_length=20, verbose_name='Tipo')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=5, verbose_name='Moneda')),
                ('banco_nombre', models.CharField(blank=True, max_length=80, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, verbose_name='N° de Cuenta')),
                ('cbu_cvu', models.CharField(blank=True, max_length=30, verbose_name='CBU / CVU / Alias')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Saldo Actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_financieras', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Financiera / Caja',
                'verbose_name_plural': 'Cuentas Financieras y Cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo', models.CharField(choices=[('RECIBIDO', 'Recibido de Cliente (En Cartera)'), ('EMITIDO', 'Emitido Propio (Cheque Diferido)')], max_length=15, verbose_name='Tipo de Cheque')),
                ('banco_emisor', models.CharField(max_length=80, verbose_name='Banco Emisor')),
                ('numero', models.CharField(max_length=40, verbose_name='Número de Cheque')),
                ('emisor_firmante', models.CharField(max_length=120, verbose_name='Emisor / Firmante')),
                ('cuit_emisor', models.CharField(blank=True, max_length=20, verbose_name='CUIT Emisor')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de Cobro / Vencimiento')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe (ARS)')),
                ('estado', models.CharField(choices=[('EN_CARTERA', 'En Cartera'), ('DEPOSITADO', 'Depositado en Banco'), ('COBRADO', 'Cobrado / Acreditado'), ('ENTREGADO_PROVEEDOR', 'Entregado / Endosado a Proveedor'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='EN_CARTERA', max_length=25, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cuenta_bancaria_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_emitidos', to='finanzas.cuenta', verbose_name='Cuenta Bancaria (si es propio)')),
                ('cuenta_corriente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_asociados', to='finanzas.cuentacorriente', verbose_name='Cliente / Proveedor Vinculado')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques (Cartera y Emitidos)',
                'ordering': ['fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso / Cobro'), ('EGRESO', 'Egreso / Pago'), ('TRANSFERENCIA', 'Transferencia entre Cuentas')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe')),
                ('moneda', models.CharField(default='ARS', max_length=5, verbose_name='Moneda')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto / Detalle')),
                ('comprobante_tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo Comprobante (Factura, Recibo)')),
                ('comprobante_nro', models.CharField(blank=True, max_length=50, verbose_name='N° Comprobante')),
                ('centro_de_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='core.centrodecosto', verbose_name='Centro de Costo Imputable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuenta', verbose_name='Cuenta Origen / Principal')),
                ('cuenta_corriente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='finanzas.cuentacorriente', verbose_name='Cuenta Corriente (Proveedor/Cliente)')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrantes', to='finanzas.cuenta', verbose_name='Cuenta Destino (si es transf.)')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='core.finca', verbose_name='Finca Imputable')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
