# Generated by Django 5.1.15 on 2026-09-19 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='conciliado',
            field=models.BooleanField(default=False, verbose_name='Conciliado'),
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_extracto', models.DateField(verbose_name='Fecha de Corte del Extracto')),
                ('saldo_extracto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo según Extracto')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo según Sistema')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Diferencia')),
                ('estado', models.CharField(choices=[('BORRADOR', 'En Proceso'), ('CERRADA', 'Conciliación Cerrada')], default='BORRADOR', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='finanzas.cuenta', verbose_name='Cuenta Bancaria')),
                ('movimientos_conciliados', models.ManyToManyField(blank=True, related_name='conciliaciones_asociadas', to='finanzas.movimientofinanciero', verbose_name='Movimientos Conciliados')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conciliación Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'ordering': ['-fecha_extracto'],
            },
        ),
    ]
