# Generated by Django 5.1.15 on 2026-09-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_movimientofinanciero_conciliado_conciliacionbancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(max_length=200, verbose_name='Rubro / Nombre de la Cuenta')),
                ('nivel', models.PositiveSmallIntegerField(default=1, verbose_name='Nivel Jerárquico')),
                ('saldo_habitual', models.CharField(blank=True, choices=[('DEUDOR', 'Deudor'), ('ACREEDOR', 'Acreedor')], default='', max_length=15, verbose_name='Saldo Habitual')),
                ('clase', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('ACTIVO_REG', 'Activo (regularizadora)'), ('PASIVO', 'Pasivo'), ('PATRIMONIO_NETO', 'Patrimonio Neto'), ('RESULTADO_POSITIVO', 'Resultado Positivo (Ingreso)'), ('RESULTADO_NEGATIVO', 'Resultado Negativo (Egreso/Costo)'), ('OTRO', 'Otro')], default='', max_length=30, verbose_name='Clase Contable')),
                ('es_imputable', models.BooleanField(default=False, help_text='Indica si permite imputación de asientos y vinculación con documentos directos.', verbose_name='¿Es Imputable?')),
                ('nota', models.TextField(blank=True, help_text='Criterio agronómico o industrial (NIC 41, almazara, exportación, etc.)', verbose_name='Nota Técnica / Criterio Olivícola')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='finanzas.cuentacontable', verbose_name='Cuenta Padre / Rubro Superior')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Cuenta del Plan de Cuentas correspondiente a esta caja o banco.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_financieras', to='finanzas.cuentacontable', verbose_name='Cuenta Contable Asociada'),
        ),
    ]
