# Generated by Django 5.1.15 on 2026-09-21 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('finanzas', '0003_cuentacontable_cuenta_cuenta_contable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título del Cuadro / Informe')),
                ('tipo_periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('CAMPANA_ANUAL', 'Campaña Anual Olivícola'), ('PERSONALIZADO', 'Período Personalizado')], default='CAMPANA_ANUAL', max_length=20, verbose_name='Tipo de Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Desde')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Hasta')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=5, verbose_name='Moneda de Presentación')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Tipo de Cambio Oficial (ARS/USD)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En Armado)'), ('REVISION', 'En Revisión de Gerencia'), ('APROBADO', 'Aprobado por Directorio')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('volumen_aceituna_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aceituna Cosechada / Molida (Kg)')),
                ('volumen_aceite_litros', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aceite Elaborado (Litros)')),
                ('notas_gerencia', models.TextField(blank=True, help_text='Comentarios de rendimiento, calidad, precios de exportación y desvíos.', verbose_name='Análisis y Conclusiones para la Gerencia')),
                ('ventas_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Ventas Netas Totales')),
                ('costo_produccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Costo de Mercaderías Vendidas / Producción')),
                ('margen_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Margen Bruto (Utilidad Bruta)')),
                ('gastos_administracion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Gastos de Administración')),
                ('gastos_comercializacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Gastos de Comercialización y Exportación')),
                ('ebitda', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Resultado Operativo (EBITDA)')),
                ('amortizaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amortizaciones y Depreciaciones')),
                ('resultados_financieros', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Resultados Financieros y por Tenencia')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Impuesto a las Ganancias y Tasas')),
                ('resultado_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Resultado Neto del Ejercicio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadros_resultado', to='core.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Cuadro de Resultados',
                'verbose_name_plural': 'Cuadros de Resultados',
                'ordering': ['-fecha_fin', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineaCuadroResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('seccion', models.CharField(choices=[('INGRESOS_OPERATIVOS', '1. Ingresos Operativos (Ventas Netas)'), ('COSTOS_PROD_AGRO', '2.1 Costos de Producción Agrícola (Campo)'), ('COSTOS_PROD_IND', '2.2 Costos Industriales (Almazara/Extracción)'), ('COSTOS_ENVASADO', '2.3 Costos de Envasado, Tapas y Etiquetas'), ('COSTOS_VENTAS', '2.4 Otros Costos de Ventas'), ('GASTOS_ADMIN', '3.1 Gastos de Administración y Estructura'), ('GASTOS_COMERCIALIZACION', '3.2 Gastos Comerciales, Logística y Exportación'), ('AMORTIZACIONES', '4. Amortizaciones y Depreciaciones'), ('RESULTADOS_FINANCIEROS', '5. Resultados Financieros y por Tenencia (NIC 41)'), ('IMPUESTOS', '6. Impuesto a las Ganancias y Tasas'), ('EXTRAORDINARIOS', '7. Resultados Extraordinarios')], default='INGRESOS_OPERATIVOS', max_length=30, verbose_name='Sección del Estado de Resultados')),
                ('monto_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Importe Real ($)')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Presupuesto ($)')),
                ('porcentaje_ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='% s/ Ventas')),
                ('desvio_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Desvío ($)')),
                ('desvio_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Desvío (%)')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones de la Línea')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.cuadroresultado', verbose_name='Cuadro de Resultados')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cuadro_resultado', to='finanzas.cuentacontable', verbose_name='Cuenta Contable Asociada')),
            ],
            options={
                'verbose_name': 'Línea de Cuadro de Resultados',
                'verbose_name_plural': 'Líneas de Cuadro de Resultados',
                'ordering': ['seccion', 'cuenta_contable__codigo'],
                'unique_together': {('cuadro', 'cuenta_contable')},
            },
        ),
    ]
