# Generated by Django 5.1.15 on 2026-09-21 03:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('finanzas', '0004_cuadroresultado_lineacuadroresultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambioMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('tc', models.DecimalField(decimal_places=2, default=Decimal('1050.00'), max_digits=12, verbose_name='Tipo de Cambio Oficial (ARS por USD)')),
                ('fuente', models.CharField(blank=True, default='Banco Nación (BNA) / Oficial', max_length=120, verbose_name='Fuente / Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_cambio', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio Mensual',
                'verbose_name_plural': 'Tipos de Cambio Mensuales',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('empresa', 'ano', 'mes')},
            },
        ),
    ]
