# Generated by Django 5.1.15 on 2026-09-21 16:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('finanzas', '0005_tipocambiomensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha', models.DateField(verbose_name='Fecha de Corte / Cierre')),
                ('hora', models.TimeField(verbose_name='Hora de Arqueo')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo según Sistema (ARS)')),
                ('saldo_real_contado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Efectivo Contado Físicamente (ARS)')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Diferencia (+ Sobrante / - Faltante)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En Conteo)'), ('CERRADO', 'Arqueo Cerrado y Validado')], default='CERRADO', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Justificación')),
                ('cuenta', models.ForeignKey(limit_choices_to={'tipo': 'CAJA_EFECTIVO'}, on_delete=django.db.models.deletion.PROTECT, related_name='arqueos', to='finanzas.cuenta', verbose_name='Caja Física')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Cierre')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra (Crédito Fiscal / Cta. a Pagar)'), ('VENTA', 'Venta (Débito Fiscal / Cta. a Cobrar)')], default='COMPRA', max_length=10, verbose_name='Tipo de Operación')),
                ('tipo_comprobante', models.CharField(choices=[('F_A', 'Factura A'), ('F_B', 'Factura B'), ('F_C', 'Factura C'), ('F_M', 'Factura M'), ('ND_A', 'Nota de Débito A'), ('ND_B', 'Nota de Débito B'), ('ND_C', 'Nota de Débito C'), ('NC_A', 'Nota de Crédito A'), ('NC_B', 'Nota de Crédito B'), ('NC_C', 'Nota de Crédito C'), ('REC_OF', 'Recibo Oficial / Comprobante X')], default='F_A', max_length=10, verbose_name='Tipo de Comprobante')),
                ('punto_de_venta', models.CharField(default='00001', max_length=5, verbose_name='Punto de Venta (PV)')),
                ('numero_comprobante', models.CharField(max_length=8, verbose_name='Número de Comprobante')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT / Identificación Tributaria')),
                ('condicion_iva', models.CharField(choices=[('RI', 'IVA Responsable Inscripto'), ('MONO', 'Responsable Monotributo'), ('EXENTO', 'IVA Exento'), ('CF', 'Consumidor Final')], default='RI', max_length=10, verbose_name='Condición Frente al IVA')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto / Descripción')),
                ('neto_gravado_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Neto Gravado 21%')),
                ('neto_gravado_10_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Neto Gravado 10.5%')),
                ('neto_gravado_27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Neto Gravado 27%')),
                ('iva_21', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA Liquidado 21%')),
                ('iva_10_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA Liquidado 10.5%')),
                ('iva_27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IVA Liquidado 27%')),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Conceptos No Gravados')),
                ('exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Operaciones Exentas')),
                ('percepcion_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Percepción de IVA')),
                ('percepcion_iibb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Percepción IIBB (Catamarca / CM)')),
                ('impuestos_internos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuestos Internos / Otros')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Importe Total Facturado')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago / Cobro'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Cancelada / Pagada Total'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado de Pago')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo Pendiente')),
                ('cae', models.CharField(blank=True, max_length=25, verbose_name='CAE / CAI')),
                ('vto_cae', models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE')),
                ('centro_de_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_fiscales', to='core.centrodecosto', verbose_name='Centro de Costo')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_fiscales', to='finanzas.cuentacontable', verbose_name='Cuenta Contable Imputable')),
                ('cuenta_corriente', models.ForeignKey(help_text='Entidad de la cuenta corriente vinculada.', on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_fiscales', to='finanzas.cuentacorriente', verbose_name='Proveedor / Cliente')),
            ],
            options={
                'verbose_name': 'Comprobante Fiscal',
                'verbose_name_plural': 'Comprobantes Fiscales (Libro IVA)',
                'ordering': ['-fecha_emision', '-id'],
                'unique_together': {('tipo_operacion', 'tipo_comprobante', 'punto_de_venta', 'numero_comprobante', 'cuit')},
            },
        ),
        migrations.CreateModel(
            name='OrdenPagoRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo', models.CharField(choices=[('OP', 'Orden de Pago (a Proveedor)'), ('RC', 'Recibo de Cobranza (de Cliente)')], default='OP', max_length=5, verbose_name='Tipo de Comprobante')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° de Orden / Recibo')),
                ('fecha', models.DateField(verbose_name='Fecha de Emisión')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe Total Abonado/Cobrado')),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo (Caja Chica)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE_PROPIO', 'Cheque Propio Emitido'), ('CHEQUE_TERCERO', 'Cheque de Tercero (Cartera)')], default='TRANSFERENCIA', max_length=20, verbose_name='Medio de Pago')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto / Motivo')),
                ('beneficiario_firmante', models.CharField(blank=True, max_length=150, verbose_name='Beneficiario / Quien Recibe')),
                ('dni_firmante', models.CharField(blank=True, max_length=30, verbose_name='DNI / CUIT de Quien Recibe')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago', to='finanzas.cheque', verbose_name='Cheque Utilizado (si aplica)')),
                ('comprobante_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibos', to='finanzas.comprobantefiscal', verbose_name='Factura Imputada (opcional)')),
                ('cuenta_corriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_y_recibos', to='finanzas.cuentacorriente', verbose_name='Proveedor / Cliente')),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_y_recibos', to='finanzas.cuenta', verbose_name='Caja o Cuenta Bancaria')),
                ('movimiento_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_recibo_origen', to='finanzas.movimientofinanciero', verbose_name='Movimiento de Tesorería Generado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'Orden de Pago / Recibo',
                'verbose_name_plural': 'Órdenes de Pago y Recibos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
