# Generated by Django 5.1.15 on 2026-09-21 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('finanzas', '0006_arqueocaja_comprobantefiscal_ordenpagorecibo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso / Cobro'), ('EGRESO', 'Egreso / Pago'), ('TRANSFERENCIA', 'Transferencia entre Cuentas')], db_index=True, max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddIndex(
            model_name='comprobantefiscal',
            index=models.Index(fields=['fecha_emision', 'tipo_operacion'], name='finanzas_co_fecha_e_05b2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobantefiscal',
            index=models.Index(fields=['cuenta_corriente', 'estado_pago'], name='finanzas_co_cuenta__15fd49_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobantefiscal',
            index=models.Index(fields=['estado_pago', 'fecha_vencimiento'], name='finanzas_co_estado__475670_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['fecha', 'tipo'], name='finanzas_mo_fecha_fcb5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['cuenta', 'fecha'], name='finanzas_mo_cuenta__fea6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofinanciero',
            index=models.Index(fields=['cuenta_corriente', 'fecha'], name='finanzas_mo_cuenta__7b0fa3_idx'),
        ),
    ]
