# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_movimientofinanciero_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantefiscal',
            name='es_oficial',
            field=models.BooleanField(default=True, help_text='Indica si es factura oficial (Blanco) o interna (Negro/2)', verbose_name='Registro Oficial (ARCA/AFIP)'),
        ),
    ]
