# Generated by Django 5.1.15 on 2026-09-27 04:11

from django.db import migrations
from django.core.management import call_command
import os
from django.conf import settings

def load_plan_cuentas(apps, schema_editor):
    # La ruta al archivo Excel
    archivo_xlsx = os.path.join(settings.BASE_DIR, 'Plan_de_Cuentas_Empresa_Olivicola.xlsx')
    
    # Asegurarnos de que el archivo existe antes de correr el comando
    if os.path.exists(archivo_xlsx):
        call_command('importar_plan_cuentas', archivo=archivo_xlsx, limpiar=True)
    else:
        print(f"ATENCION: No se encontró el archivo {archivo_xlsx}. Se omitirá la carga del Plan de Cuentas.")

def revert_plan_cuentas(apps, schema_editor):
    pass # No borramos las cuentas en revert para no romper dependencias

class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_comprobantefiscal_es_oficial'),
    ]

    operations = [
        migrations.RunPython(load_plan_cuentas, revert_plan_cuentas)
    ]
