# Generated by Django 5.1.15 on 2026-09-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_populate_plan_cuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantefiscal',
            name='tipo_comprobante',
            field=models.CharField(choices=[('F_A', 'Factura A'), ('F_B', 'Factura B'), ('F_C', 'Factura C'), ('F_M', 'Factura M'), ('ND_A', 'Nota de Débito A'), ('ND_B', 'Nota de Débito B'), ('ND_C', 'Nota de Débito C'), ('NC_A', 'Nota de Crédito A'), ('NC_B', 'Nota de Crédito B'), ('NC_C', 'Nota de Crédito C'), ('REC_OF', 'Recibo Oficial / Recibo X'), ('COMP_X', 'Comprobante Interno (No Fiscal)'), ('PRESUP', 'Presupuesto / Proforma'), ('REM_INT', 'Remito Valorizado')], default='F_A', max_length=10, verbose_name='Tipo de Comprobante'),
        ),
    ]
