# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Depósito')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Interno')),
                ('es_deposito_central', models.BooleanField(default=False, verbose_name='¿Es Depósito Central?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='core.finca', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['finca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='Código Insumo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Insumo / Producto')),
                ('unidad_medida', models.CharField(choices=[('LTS', 'Litros (Lts)'), ('KG', 'Kilogramos (Kg)'), ('GRS', 'Gramos (Grs)'), ('UNIDAD', 'Unidad'), ('BINS', 'Bins de Cosecha'), ('BOLSA', 'Bolsas / Sacos'), ('M3', 'Metros Cúbicos')], default='LTS', max_length=20, verbose_name='Unidad de Medida')),
                ('principio_activo', models.CharField(blank=True, max_length=120, verbose_name='Principio Activo / Composición')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Total Global')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Stock Mínimo de Alerta')),
                ('costo_unitario_ars', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio Promedio Ponderado en ARS', max_digits=12, verbose_name='Costo Unitario PPP (ARS)')),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Unitario PPP (USD)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoriainsumo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Maquinaria')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Modelo')),
                ('tipo', models.CharField(choices=[('TRACTOR', 'Tractor Agrícola'), ('COSECHADORA', 'Cosechadora Vibradora de Tronco'), ('ATOMIZADORA', 'Atomizadora / Pulverizadora'), ('DESMALEZADORA', 'Desmalezadora / Rastra'), ('CAMION', 'Camión / Transporte'), ('CAMIONETA', 'Camioneta / Utilitario'), ('OTRO', 'Otro Equipo')], default='TRACTOR', max_length=30, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo')),
                ('ano_fabricacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('horas_o_km_acumulados', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Horas / Km Acumulados')),
                ('estado', models.CharField(choices=[('OPERATIVA', 'Operativa'), ('EN_MANTENIMIENTO', 'En Taller / Mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio'), ('BAJA', 'Dada de Baja')], default='OPERATIVA', max_length=25, verbose_name='Estado')),
                ('fecha_ultimo_service', models.DateField(blank=True, null=True, verbose_name='Fecha Último Mantenimiento')),
                ('finca_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finca', verbose_name='Finca Asignada')),
            ],
            options={
                'verbose_name': 'Máquina / Vehículo',
                'verbose_name_plural': 'Parque de Maquinarias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Service Preventivo (Filtros, Aceite)'), ('CORRECTIVO', 'Reparación Correctiva / Rotura'), ('LUBRICACION', 'Engrase y Revisión General')], default='PREVENTIVO', max_length=25, verbose_name='Tipo de Mantenimiento')),
                ('horas_maquina', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horas/Km al momento')),
                ('descripcion', models.TextField(verbose_name='Detalle de las tareas realizadas')),
                ('costo_total_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Total (ARS)')),
                ('taller_o_proveedor', models.CharField(blank=True, max_length=120, verbose_name='Taller / Mecánico Responsable')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Máquina',
                'verbose_name_plural': 'Mantenimientos de Máquinas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tipo', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra / Remito'), ('SALIDA_PARTE_DIARIO', 'Salida por Parte Diario / Cuadro'), ('TRANSFERENCIA', 'Transferencia entre Depósitos'), ('AJUSTE_POSITIVO', 'Ajuste de Inventario (+)'), ('AJUSTE_NEGATIVO', 'Ajuste de Inventario (-)'), ('SALIDA_MERMA', 'Merma / Vencimiento')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Unitario al Movimiento')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora del Movimiento')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo / Concepto')),
                ('referencia_origen', models.CharField(blank=True, help_text='ID Parte Diario, N° Remito o Factura', max_length=100, verbose_name='Documento de Referencia')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario.deposito', verbose_name='Depósito Origen')),
                ('deposito_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino_transferencia', to='inventario.deposito', verbose_name='Depósito Destino (si es transf.)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo', verbose_name='Insumo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Remito')),
                ('tipo', models.CharField(choices=[('ENTRADA_PROVEEDOR', 'Entrada desde Proveedor'), ('SALIDA_CLIENTE', 'Salida a Cliente / Exportación'), ('INTERNO', 'Traslado Interno entre Fincas')], max_length=30, verbose_name='Tipo de Remito')),
                ('fecha', models.DateField(verbose_name='Fecha de Emisión / Recepción')),
                ('entidad_nombre', models.CharField(blank=True, help_text='Nombre del proveedor remitente o cliente destinatario', max_length=150, verbose_name='Proveedor / Cliente')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado / Ingresado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='remitos/', verbose_name='Archivo PDF / Foto')),
                ('finca_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_entrantes', to='core.finca', verbose_name='Finca Destino')),
                ('finca_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_salientes', to='core.finca', verbose_name='Finca Origen')),
            ],
            options={
                'verbose_name': 'Remito',
                'verbose_name_plural': 'Remitos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad_declarada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Declarada')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Real Recibida')),
                ('precio_unitario_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario (ARS)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo', verbose_name='Insumo')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.remito', verbose_name='Remito')),
            ],
            options={
                'verbose_name': 'Ítem de Remito',
                'verbose_name_plural': 'Ítems de Remito',
            },
        ),
        migrations.CreateModel(
            name='StockPorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cantidad en Depósito')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='inventario.deposito', verbose_name='Depósito')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias_por_deposito', to='inventario.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Existencia por Depósito',
                'verbose_name_plural': 'Existencias por Depósito',
                'unique_together': {('deposito', 'insumo')},
            },
        ),
    ]
