# Generated by Django 5.1.15 on 2026-09-20 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0002_movimientofinanciero_conciliado_conciliacionbancaria'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='N° de OC')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada / Enviada al proveedor'), ('RECIBIDA', 'Recibida Totalmente'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('registrar_deuda_al_aprobar', models.BooleanField(default=False, help_text='Si está activo, la deuda se acredita en la cuenta corriente del proveedor al aprobar la OC. Si no, se espera al momento de recepción/factura.', verbose_name='Registrar deuda al aprobar OC')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_estimado_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Estimado (ARS)')),
                ('finca_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='core.finca', verbose_name='Finca Destino')),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo_entidad': 'PROVEEDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='finanzas.cuentacorriente', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Solicitada')),
                ('precio_unitario_estimado_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario Est. (ARS)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo', verbose_name='Insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordendecompra', verbose_name='OC')),
            ],
            options={
                'verbose_name': 'Ítem de OC',
                'verbose_name_plural': 'Ítems de OC',
            },
        ),
        migrations.CreateModel(
            name='RecepcionMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('numero_remito_proveedor', models.CharField(blank=True, max_length=60, verbose_name='N° Remito Proveedor')),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=60, verbose_name='N° Factura Proveedor')),
                ('registrar_deuda_al_confirmar', models.BooleanField(default=True, help_text='Si está activo, al confirmar la recepción se actualizará la cuenta corriente del proveedor con el importe real de la factura.', verbose_name='Registrar deuda en cta. cte. al confirmar')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada — Stock Impactado'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_real_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Real Facturado (ARS)')),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito', verbose_name='Depósito de Ingreso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.ordendecompra', verbose_name='Orden de Compra')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable Recepción')),
            ],
            options={
                'verbose_name': 'Recepción de Mercadería',
                'verbose_name_plural': 'Recepciones de Mercadería',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cantidad_en_oc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cant. en OC')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cant. Real Recibida')),
                ('precio_unitario_real_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario Real (ARS)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo', verbose_name='Insumo')),
                ('movimiento_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientostock', verbose_name='Movimiento de Stock Generado')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.recepcionmercaderia', verbose_name='Recepción')),
            ],
            options={
                'verbose_name': 'Ítem de Recepción',
                'verbose_name_plural': 'Ítems de Recepción',
            },
        ),
    ]
