# Generated by Django 5.1.15 on 2026-09-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentacontable_cuenta_cuenta_contable'),
        ('inventario', '0002_ordendecompra_itemordendecompra_recepcionmercaderia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainsumo',
            name='cuenta_contable_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_insumo_activo', to='finanzas.cuentacontable', verbose_name='Cuenta Contable de Existencias (Activo)'),
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='cuenta_contable_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_insumo_gasto', to='finanzas.cuentacontable', verbose_name='Cuenta Contable de Consumo/Gasto'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Opcional: Si no se especifica, toma las cuentas de su categoría.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_vinculados', to='finanzas.cuentacontable', verbose_name='Cuenta Contable Específica'),
        ),
    ]
