# Generated by Django 5.1.15 on 2026-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoriainsumo_cuenta_contable_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='firma_aclaracion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo / Relación'),
        ),
        migrations.AddField(
            model_name='remito',
            name='firma_digital',
            field=models.TextField(blank=True, verbose_name='Firma Digital (Base64 PNG)'),
        ),
        migrations.AddField(
            model_name='remito',
            name='firma_dni_receptor',
            field=models.CharField(blank=True, max_length=30, verbose_name='DNI / CUIT Receptor'),
        ),
        migrations.AddField(
            model_name='remito',
            name='firma_fecha_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Firma'),
        ),
        migrations.AddField(
            model_name='remito',
            name='firma_geolocalizacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Coordenadas GPS'),
        ),
        migrations.AddField(
            model_name='remito',
            name='firma_nombre_receptor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre Receptor'),
        ),
        migrations.AddField(
            model_name='remito',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=25, verbose_name='Patente / Dominio Vehículo'),
        ),
        migrations.AddField(
            model_name='remito',
            name='transportista_nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Transportista / Chofer'),
        ),
    ]
