# Generated by Django 5.1.15 on 2026-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodecosto_cuenta_contable_defecto'),
        ('inventario', '0004_remito_firma_aclaracion_remito_firma_digital_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='remito',
            index=models.Index(fields=['fecha', 'tipo'], name='inventario__fecha_d25a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='remito',
            index=models.Index(fields=['estado', 'fecha'], name='inventario__estado_f8ca9d_idx'),
        ),
    ]
