# Generated by Django 5.1 on 2026-10-07 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
        ('inventario', '0005_remito_inventario__fecha_d25a8b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='factura_referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Factura / OC de Referencia'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='valor_adquisicion_ars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Valor de Adquisición (ARS)'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Interno')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Descripción')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca y Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible en Pañol'), ('ASIGNADA', 'Asignada / En Uso'), ('MANTENIMIENTO', 'En Reparación / Mantenimiento'), ('PERDIDA', 'Perdida / Robada'), ('BAJA', 'Dada de Baja por Rotura')], default='DISPONIBLE', max_length=30, verbose_name='Estado Físico')),
                ('valor_adquisicion_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Adquisición (ARS)')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('factura_referencia', models.CharField(blank=True, max_length=100, verbose_name='N° Factura / Remito')),
                ('deposito_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herramientas_base', to='inventario.deposito', verbose_name='Pañol / Depósito Base')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_prestamo', models.DateTimeField(verbose_name='Fecha y Hora de Préstamo')),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True, verbose_name='Devolución Esperada')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo (No Devuelto)'), ('DEVUELTO', 'Devuelto')], default='ACTIVO', max_length=20, verbose_name='Estado del Préstamo')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Devolución')),
                ('estado_entrega_final', models.CharField(blank=True, help_text='Ej: Buen estado, Roto, Incompleto', max_length=50, verbose_name='Estado al devolver')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herramientas_prestadas', to='personal.empleado', verbose_name='Empleado Asignado')),
                ('finca_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finca', verbose_name='Finca de Uso')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.herramienta', verbose_name='Herramienta')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Asignación de Herramienta',
                'verbose_name_plural': 'Asignaciones de Herramientas',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
