# Generated by Django 5.1 on 2026-10-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
        ('inventario', '0006_herramienta_asignacionherramienta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionherramienta',
            name='cuadro_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campos.cuadro', verbose_name='Cuadro de Uso'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='cuadro_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campos.cuadro', verbose_name='Cuadro Asignado'),
        ),
    ]
