# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('dias_jornales_computados', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Días/Jornales Computados (Asistencia)')),
                ('horas_normales', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horas Normales')),
                ('horas_extras', models.DecimalField(decimal_places=1, default=0.0, max_digits=6, verbose_name='Horas Extras')),
                ('total_bruto_remunerativo_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Bruto Remunerativo')),
                ('total_no_remunerativo_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total No Remunerativo')),
                ('total_retenciones_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Retenciones / Descuentos')),
                ('neto_a_cobrar_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sueldo Neto a Cobrar (ARS)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADO', 'Calculado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado')], default='CALCULADO', max_length=20, verbose_name='Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='personal.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Liquidación de Empleado',
                'verbose_name_plural': 'Liquidaciones de Empleados',
                'ordering': ['empleado__apellido', 'empleado__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo_concepto', models.CharField(max_length=30, verbose_name='Código Concepto')),
                ('descripcion', models.CharField(max_length=120, verbose_name='Descripción Concepto')),
                ('tipo', models.CharField(choices=[('REMUNERATIVO', 'Haber Remunerativo'), ('NO_REMUNERATIVO', 'Haber No Remunerativo'), ('RETENCION', 'Retención / Descuento de Ley')], max_length=20, verbose_name='Tipo de Concepto')),
                ('cantidad_o_porcentaje', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Unidades / %')),
                ('importe_ars', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe (ARS)')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liquidacion.liquidacionempleado', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Ítem de Liquidación',
                'verbose_name_plural': 'Ítems de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes (1-12)')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('1Q', '1ra Quincena (Días 1 al 15)'), ('2Q', '2da Quincena (Días 16 a fin de mes)'), ('M', 'Mes Completo')], default='1Q', max_length=5, verbose_name='Tipo de Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto para Novedades'), ('PROCESANDO', 'Procesando en Celery...'), ('CALCULADO', 'Calculado / En Revisión'), ('CERRADO', 'Cerrado y Liquidado')], default='ABIERTO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Período de Liquidación',
                'verbose_name_plural': 'Períodos de Liquidación',
                'ordering': ['-ano', '-mes', '-tipo'],
                'unique_together': {('mes', 'ano', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='liquidacionempleado',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='liquidacion.periodoliquidacion', verbose_name='Período'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionempleado',
            unique_together={('periodo', 'empleado')},
        ),
    ]
