# Generated by Django 5.1.15 on 2026-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código de Cuadro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre / Denominación')),
                ('hectareas_netas', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hectáreas Netas')),
                ('variedad_olivo', models.CharField(choices=[('ARAUCO', 'Arauco (Criolla)'), ('ARBEQUINA', 'Arbequina'), ('PICUAL', 'Picual'), ('FRANTOIO', 'Frantoio'), ('MANZANILLA', 'Manzanilla'), ('CORATINA', 'Coratina'), ('CHANGLOT', 'Changlot Real'), ('HOJIBLANCA', 'Hojiblanca'), ('EMPELTRE', 'Empeltre'), ('OTRA', 'Otra Variedad')], default='ARAUCO', max_length=30, verbose_name='Variedad de Olivo')),
                ('ano_plantacion', models.PositiveIntegerField(verbose_name='Año de Plantación')),
                ('densidad_plantas_ha', models.PositiveIntegerField(default=300, help_text='Ej: 250-400 tradicional, 800 intensivo, 1600+ superintensivo', verbose_name='Densidad (plantas/ha)')),
                ('marco_plantacion', models.CharField(blank=True, help_text='Ej: 7x5 m, 6x4 m, 4x1.5 m', max_length=30, verbose_name='Marco de Plantación')),
                ('sistema_riego', models.CharField(choices=[('GOTEO', 'Goteo automatizado'), ('SURCO', 'Surco / Inundación'), ('ASPERSION', 'Microaspersión'), ('SECANO', 'Secano')], default='GOTEO', max_length=20, verbose_name='Sistema de Riego')),
                ('estado_fitosanitario', models.CharField(blank=True, default='Óptimo', max_length=100, verbose_name='Estado Fitosanitario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Agronómicas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cuadro',
                'verbose_name_plural': 'Cuadros',
                'ordering': ['finca', 'codigo'],
                'permissions': (('gestionar_cuadro', 'Puede gestionar y editar cuadro'),),
            },
        ),
        migrations.CreateModel(
            name='LoteDeCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('campana', models.CharField(help_text='Ej: 2025/2026', max_length=20, verbose_name='Campaña Agrícola')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('kg_cosechados', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kilogramos Cosechados')),
                ('destino', models.CharField(choices=[('ACEITE_ALMAZARA', 'Aceite de Oliva (Almazara)'), ('ACEITUNA_MESA_VERDE', 'Aceituna de Mesa (Verde)'), ('ACEITUNA_MESA_NEGRA', 'Aceituna de Mesa (Negra / Madura)')], default='ACEITE_ALMAZARA', max_length=30, verbose_name='Destino de la Cosecha')),
                ('rendimiento_graso_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de materia grasa estimado en laboratorio para almazara', max_digits=5, null=True, verbose_name='Rendimiento Graso (%)')),
                ('calidad_observaciones', models.TextField(blank=True, verbose_name='Notas de Calidad / Acidez')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('LIQUIDADO', 'Liquidado a Fábrica')], default='EN_CURSO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Lote de Cosecha',
                'verbose_name_plural': 'Lotes de Cosecha',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
