# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadro',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadros', to='core.finca', verbose_name='Finca'),
        ),
        migrations.AddField(
            model_name='lotedecosecha',
            name='cuadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_cosecha', to='campos.cuadro', verbose_name='Cuadro'),
        ),
        migrations.AlterUniqueTogether(
            name='cuadro',
            unique_together={('finca', 'codigo')},
        ),
    ]
