# Generated by Django 5.1.15 on 2026-09-20 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('campana', models.CharField(max_length=20, verbose_name='Campaña')),
                ('tipo_evento', models.CharField(choices=[('PODA', 'Poda'), ('RALEO', 'Raleo de Frutos'), ('RIEGO_AUXILIO', 'Riego de Auxilio'), ('FITOSANITARIO', 'Aplicación Fitosanitaria'), ('FERTILIZACION', 'Fertilización'), ('ANALISIS_SUELO', 'Análisis de Suelo'), ('ANALISIS_FOLIAR', 'Análisis Foliar'), ('VISITA_TECNICA', 'Visita Técnica / Agronómica'), ('OTRO', 'Otro Evento')], max_length=25, verbose_name='Tipo de Evento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción / Detalle')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='campos.cuadro', verbose_name='Cuadro')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Evento de Cuadro',
                'verbose_name_plural': 'Eventos de Cuadros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFenologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('campana', models.CharField(help_text='Ej: 2025/2026', max_length=20, verbose_name='Campaña Agrícola')),
                ('fecha', models.DateField(verbose_name='Fecha de Observación')),
                ('fase_vegetativa', models.CharField(choices=[('REPOSO', 'Reposo Invernal'), ('BROTACION', 'Brotación / Hinchazón Yemas'), ('FLORACION', 'Floración'), ('CUAJADO', 'Cuajado de Frutos'), ('CRECIMIENTO', 'Crecimiento del Fruto'), ('ENVERO', 'Envero / Cambio de Color'), ('MADUREZ', 'Madurez Comercial'), ('POSTCOSECHA', 'Post-Cosecha')], default='BROTACION', max_length=20, verbose_name='Fase Fenológica')),
                ('grados_dia_acumulados', models.DecimalField(decimal_places=1, default=0.0, help_text='Grados Día de Crecimiento desde inicio de campaña', max_digits=7, verbose_name='GDC Acumulados')),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp. Mínima (°C)')),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp. Máxima (°C)')),
                ('riesgo_fitosanitario', models.CharField(choices=[('BAJO', 'Sin riesgo aparente'), ('MODERADO', 'Monitoreo requerido'), ('ALTO', 'Intervención urgente')], default='BAJO', max_length=10, verbose_name='Riesgo Fitosanitario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Agronómicas')),
                ('cuadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_fenologicos', to='campos.cuadro', verbose_name='Cuadro')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico / Agrónomo')),
            ],
            options={
                'verbose_name': 'Registro Fenológico',
                'verbose_name_plural': 'Registros Fenológicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
