# Generated by Django 5.1.15 on 2026-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_eventocuadro_registrofenologico'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lotedecosecha',
            index=models.Index(fields=['campana'], name='campos_lote_campana_da8d40_idx'),
        ),
        migrations.AddIndex(
            model_name='lotedecosecha',
            index=models.Index(fields=['cuadro', 'campana'], name='campos_lote_cuadro__56a486_idx'),
        ),
    ]
