# Generated by Django 5.1.15 on 2026-09-27 03:47

from django.db import migrations
from django.utils.text import slugify

def populate_fincas(apps, schema_editor):
    Empresa = apps.get_model('core', 'Empresa')
    Finca = apps.get_model('core', 'Finca')
    Cuadro = apps.get_model('campos', 'Cuadro')

    empresa = Empresa.objects.first()
    if not empresa:
        # Si no hay empresa por algun motivo, creamos una para que no falle la migracion
        empresa = Empresa.objects.create(
            razon_social="Empresa S.A.",
            cuit="20409378472",
            condicion_iva="RI"
        )

    fincas_data = [
        {"nombre": "Campo 2", "ubicacion": "Vichigasta", "ha": 80.0},
        {"nombre": "Cerrillos", "ubicacion": "Vichigasta", "ha": 95.0},
        {"nombre": "Chilecito", "ubicacion": "Chilecito", "ha": 60.0},
        {"nombre": "Rincón", "ubicacion": "Vichigasta", "ha": 120.0},
        {"nombre": "campo10", "ubicacion": "Nonogasta/chilecito", "ha": 50.0},
    ]

    # Crear Fincas
    fincas_creadas = {}
    for idx, fdata in enumerate(fincas_data):
        codigo_str = slugify(fdata["nombre"])[:20].upper()
        # Ensure codigo is unique just in case
        if Finca.objects.filter(codigo=codigo_str).exists():
            codigo_str = f"{codigo_str}_{idx}"

        finca, created = Finca.objects.update_or_create(
            nombre=fdata["nombre"],
            empresa=empresa,
            defaults={
                "codigo": codigo_str,
                "superficie_total_ha": fdata["ha"],
                "ubicacion": fdata["ubicacion"],
                "tipo_riego_principal": "GOTEO"
            }
        )
        fincas_creadas[fdata["nombre"]] = finca

    # Crear Cuadro para campo10
    finca_campo10 = fincas_creadas.get("campo10")
    if finca_campo10:
        obs_text = "Hileras: 30\nMetros/hilera: 30\nPlantas Totales: 50\nFallas: 6 (12%)\nProductivas: 44"
        # Usamos una densidad que concuerde aprox, 50 plantas en 10 ha = 5 plantas/ha (esto es para el model field)
        # o quizas es un error y las plantas son 50 por hectarea. Lo guardamos en observaciones para estar seguros.
        Cuadro.objects.update_or_create(
            finca=finca_campo10,
            codigo="SITIO1",
            defaults={
                "nombre": "sitio1",
                "hectareas_netas": 10.0,
                "variedad_olivo": "ARAUCO",
                "ano_plantacion": 2020,  # Valor por defecto
                "densidad_plantas_ha": 5, # 50/10=5
                "marco_plantacion": "30 m/hilera",
                "sistema_riego": "GOTEO",
                "observaciones": obs_text
            }
        )


def revert_fincas(apps, schema_editor):
    pass # No eliminamos las fincas al revertir para no borrar datos importantes


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_lotedecosecha_campos_lote_campana_da8d40_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_fincas, revert_fincas),
    ]
