# Generated by Django 5.1.15 on 2026-09-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0005_populate_fincas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedecosecha',
            name='precio_venta_estimado_por_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia por kilogramo para calcular ingreso y margen estimado.', max_digits=10, null=True, verbose_name='Precio de Venta Estimado (ARS/kg)'),
        ),
    ]
