# Generated by Django 5.1.15 on 2026-09-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de Legajo')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('dni_cuil', models.CharField(max_length=20, unique=True, verbose_name='CUIL / DNI')),
                ('rol_laboral', models.CharField(choices=[('PEON_GENERAL', 'Peón General Rural'), ('TRACTORISTA', 'Tractorista / Maquinista'), ('ENCARGADO_CUADRILLA', 'Encargado de Cuadrilla'), ('CAPATAZ_FINCA', 'Capataz de Finca'), ('REGADOR', 'Especialista en Riego'), ('PODADOR', 'Podador Especializado'), ('COSECHERO', 'Cosechero Temporario'), ('MECANICO', 'Mecánico / Taller'), ('OPERARIO_ALMAZARA', 'Operario Almazara / Fábrica'), ('ADMINISTRATIVO', 'Administración / RRHH')], default='PEON_GENERAL', max_length=30, verbose_name='Puesto / Categoría')),
                ('modalidad', models.CharField(choices=[('JORNAL', 'Jornal Diario Rural (UATRE)'), ('MENSUAL', 'Mensualizado Permanente'), ('DESTAJO', 'A Destajo / Al Tanto (Cosecha/Poda)')], default='JORNAL', max_length=20, verbose_name='Modalidad de Contratación')),
                ('valor_jornal_base_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Jornal / Sueldo Base (ARS)')),
                ('valor_hora_extra_ars', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Hora Extra (ARS)')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('cbu_alias', models.CharField(blank=True, max_length=60, verbose_name='CBU / Alias Bancario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('finca_habitual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados_asignados', to='core.finca', verbose_name='Finca Habitual')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Personal / Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('dni_cuil', models.CharField(max_length=20, unique=True, verbose_name='DNI / CUIL')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=40, verbose_name='Teléfono de Contacto')),
                ('puesto_aspirado', models.CharField(max_length=80, verbose_name='Puesto Aspirado')),
                ('alta_temprana_afip_numero', models.CharField(blank=True, max_length=50, verbose_name='N° Alta Temprana AFIP')),
                ('apto_medico', models.BooleanField(default=False, verbose_name='Apto Médico Vigente')),
                ('estado', models.CharField(choices=[('POSTULADO', 'Postulación Recibida'), ('EN_EVALUACION', 'En Evaluación Médica/Antecedentes'), ('ALTA_AFIP', 'Alta Temprana AFIP Generada'), ('CONTRATADO', 'Contratado / Activo en ERP'), ('RECHAZADO', 'Rechazado / Descartado')], default='POSTULADO', max_length=25, verbose_name='Estado de la Solicitud')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('empleado_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripcion_origen', to='personal.empleado', verbose_name='Legajo Creado')),
                ('finca_postulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.finca', verbose_name='Finca de Trabajo')),
            ],
            options={
                'verbose_name': 'Inscripción de Personal',
                'verbose_name_plural': 'Inscripciones y Altas de Personal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE_INJUSTIFICADO', 'Ausente Injustificado'), ('AUSENTE_JUSTIFICADO', 'Ausente Justificado'), ('LLUVIA_CLIMA', 'Suspensión por Lluvia/Clima'), ('ACCIDENTE_ART', 'Accidente / ART'), ('LICENCIA', 'Licencia / Vacaciones'), ('FERIADO_TRABAJADO', 'Feriado Trabajado')], default='PRESENTE', max_length=30, verbose_name='Estado de Asistencia')),
                ('horas_normales', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='Horas Normales')),
                ('horas_extras', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Horas Extras')),
                ('jornal_computado', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 jornal entero, 0.5 medio jornal, 0 si ausente', max_digits=3, verbose_name='Jornal Computado')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='personal.empleado', verbose_name='Empleado')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_diarias', to='core.finca', verbose_name='Finca de Jornada')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', 'empleado__apellido'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
