# Generated by Django 5.1.15 on 2026-09-20 21:14 (modified to handle existing rows)

import uuid
from django.db import migrations, models


def asignar_uuids_unicos(apps, schema_editor):
    """Asigna un UUID único a cada empleado existente antes de aplicar la restricción UNIQUE."""
    Empleado = apps.get_model('personal', 'Empleado')
    for empleado in Empleado.objects.all():
        empleado.codigo_qr_uuid = uuid.uuid4()
        empleado.save(update_fields=['codigo_qr_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        # Primero agregar el campo SIN restricción unique para poder asignar valores
        migrations.AddField(
            model_name='empleado',
            name='codigo_qr_uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Identificador único para el fichaje por escaneo de QR',
                verbose_name='Código QR Único',
                unique=False,  # Temporalmente sin unique
            ),
        ),
        # Luego asignar UUIDs únicos a todos los registros existentes
        migrations.RunPython(asignar_uuids_unicos, migrations.RunPython.noop),
        # Finalmente aplicar la restricción unique
        migrations.AlterField(
            model_name='empleado',
            name='codigo_qr_uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Identificador único para el fichaje por escaneo de QR',
                unique=True,
                verbose_name='Código QR Único',
            ),
        ),
    ]
