# Generated by Django 5.1.15 on 2026-09-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_lotedecosecha_campos_lote_campana_da8d40_idx_and_more'),
        ('core', '0003_usuario_supabase_uid'),
        ('personal', '0002_empleado_codigo_qr_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('semana_inicio', models.DateField(verbose_name='Semana (Inicio)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='core.finca', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-semana_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TareaOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('actividad', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, help_text='0 = sin meta', max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('gente', models.PositiveIntegerField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta')], default='NORMAL', max_length=20)),
                ('linea_producto', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('cuadro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campos.cuadro')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.finca')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='personal.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Tarea de Orden',
                'verbose_name_plural': 'Tareas de Orden',
                'ordering': ['created_at'],
            },
        ),
    ]
