# Generated by Django 5.1.15 on 2026-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_ordentrabajo_tareaordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tareaordentrabajo',
            name='cantidad_completada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Completada'),
        ),
        migrations.AddField(
            model_name='tareaordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
